/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

/**
 *
 * @author samue
 */
public class InterfazCompany extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCompany
     */
    public InterfazCompany() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        LabelDevelop = new javax.swing.JLabel();
        narrativaLabel = new javax.swing.JLabel();
        NivelLabel = new javax.swing.JLabel();
        LogicaLabel = new javax.swing.JLabel();
        IntegradorLabel = new javax.swing.JLabel();
        DLCLabel = new javax.swing.JLabel();
        EntradaNarrativa = new javax.swing.JTextField();
        EntradaNiveles = new javax.swing.JTextField();
        EntradaLogica = new javax.swing.JTextField();
        EntradaDLC = new javax.swing.JTextField();
        EntradaIntegrador = new javax.swing.JTextField();
        agregarNarrativaBTN = new javax.swing.JButton();
        QuitarNarrativaBTN = new javax.swing.JButton();
        AgregarNivelesBTN = new javax.swing.JButton();
        AgregarLogicaBTN = new javax.swing.JButton();
        AgregarIntegradorBTN = new javax.swing.JButton();
        AgregarDLCBTN = new javax.swing.JButton();
        RestarNivelesBTN = new javax.swing.JButton();
        RestarLogicaBTN = new javax.swing.JButton();
        RestarDLCBTN = new javax.swing.JButton();
        RestarIntegradorBTN = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelDevelop.setText("Desarrolladores");

        narrativaLabel.setText("Narrativa");

        NivelLabel.setText("Niveles");

        LogicaLabel.setText("Logica");

        IntegradorLabel.setText("Integrator");

        DLCLabel.setText("DLC");

        EntradaNarrativa.setText("0");
        EntradaNarrativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNarrativaActionPerformed(evt);
            }
        });

        EntradaNiveles.setText("0");
        EntradaNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaNivelesActionPerformed(evt);
            }
        });

        EntradaLogica.setText("0");
        EntradaLogica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaLogicaActionPerformed(evt);
            }
        });

        EntradaDLC.setText("0");
        EntradaDLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDLCActionPerformed(evt);
            }
        });

        EntradaIntegrador.setText("0");
        EntradaIntegrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaIntegradorActionPerformed(evt);
            }
        });

        agregarNarrativaBTN.setText("+");
        agregarNarrativaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarNarrativaBTNActionPerformed(evt);
            }
        });

        QuitarNarrativaBTN.setText("-");

        AgregarNivelesBTN.setText("+");
        AgregarNivelesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNivelesBTNActionPerformed(evt);
            }
        });

        AgregarLogicaBTN.setText("+");
        AgregarLogicaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLogicaBTNActionPerformed(evt);
            }
        });

        AgregarIntegradorBTN.setText("+");
        AgregarIntegradorBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarIntegradorBTNActionPerformed(evt);
            }
        });

        AgregarDLCBTN.setText("+");
        AgregarDLCBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDLCBTNActionPerformed(evt);
            }
        });

        RestarNivelesBTN.setText("-");

        RestarLogicaBTN.setText("-");

        RestarDLCBTN.setText("-");

        RestarIntegradorBTN.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogicaLabel)
                    .addComponent(DLCLabel)
                    .addComponent(IntegradorLabel)
                    .addComponent(NivelLabel)
                    .addComponent(narrativaLabel))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EntradaNarrativa, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(EntradaNiveles)
                    .addComponent(EntradaLogica)
                    .addComponent(EntradaDLC)
                    .addComponent(EntradaIntegrador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(agregarNarrativaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuitarNarrativaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AgregarNivelesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RestarNivelesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AgregarLogicaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RestarLogicaBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AgregarDLCBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RestarDLCBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AgregarIntegradorBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RestarIntegradorBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(935, 935, 935))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LabelDevelop)
                .addGap(941, 941, 941))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(LabelDevelop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(narrativaLabel)
                    .addComponent(EntradaNarrativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarNarrativaBTN)
                    .addComponent(QuitarNarrativaBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NivelLabel)
                        .addComponent(EntradaNiveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RestarNivelesBTN)
                        .addComponent(AgregarNivelesBTN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LogicaLabel)
                    .addComponent(EntradaLogica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RestarLogicaBTN)
                    .addComponent(AgregarLogicaBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DLCLabel)
                    .addComponent(EntradaDLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarDLCBTN)
                    .addComponent(RestarDLCBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntegradorLabel)
                    .addComponent(EntradaIntegrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarIntegradorBTN)
                    .addComponent(RestarIntegradorBTN))
                .addContainerGap(421, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaNarrativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNarrativaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNarrativaActionPerformed
    int contadorNarrativa=0;
    int contadorNiveles=0;
    int contadorSprites=0;
    int contadorLogica=0;
    int contadorDLC=0;
    int contadorIntegrador=0; 
    //int totalsuma=contadorNarrativa+contadorNiveles+contadorSprites+contadorLogica+contadorDLC+contadorIntegrador;
    
    private void agregarNarrativaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarNarrativaBTNActionPerformed
        // TODO add your handling code here:
        
  contadorNarrativa++;
    int totalsuma=contadorNarrativa+contadorNiveles+contadorSprites+contadorLogica+contadorDLC+contadorIntegrador;
    if(totalsuma<=13){
        
    EntradaNarrativa.setText(String.valueOf(contadorNarrativa));}
    else{
    
    }

    
   

    
    // Verificar si la suma total supera el límite de 13
    //int sumaTotal = valorActual + valorCuadro2 + valorCuadro3 + valorCuadro4 + valorCuadro5 + 1;
    }//GEN-LAST:event_agregarNarrativaBTNActionPerformed

    private void EntradaLogicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaLogicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaLogicaActionPerformed

    private void AgregarNivelesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNivelesBTNActionPerformed
        // TODO add your handling code here:
        
    contadorNiveles++;
    int totalsuma=contadorNarrativa+contadorNiveles+contadorSprites+contadorLogica+contadorDLC+contadorIntegrador;
    if(totalsuma<=13){EntradaNiveles.setText(String.valueOf(contadorNiveles));}
        
    }//GEN-LAST:event_AgregarNivelesBTNActionPerformed

    private void AgregarLogicaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLogicaBTNActionPerformed
        // TODO add your handling code here:
        
    contadorLogica++;
    int totalsuma=contadorNarrativa+contadorNiveles+contadorSprites+contadorLogica+contadorDLC+contadorIntegrador;
    if(totalsuma<=13){EntradaLogica.setText(String.valueOf(contadorLogica));}
    
    }//GEN-LAST:event_AgregarLogicaBTNActionPerformed

    private void AgregarDLCBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDLCBTNActionPerformed
        // TODO add your handling code here:
    contadorDLC++;
    int totalsuma=contadorNarrativa+contadorNiveles+contadorSprites+contadorLogica+contadorDLC+contadorIntegrador;
    if(totalsuma<=13){EntradaDLC.setText(String.valueOf(contadorDLC));}
    
        
    }//GEN-LAST:event_AgregarDLCBTNActionPerformed

    private void AgregarIntegradorBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarIntegradorBTNActionPerformed
        // TODO add your handling code here:
        
    contadorIntegrador++;
    int totalsuma=contadorNarrativa+contadorNiveles+contadorSprites+contadorLogica+contadorDLC+contadorIntegrador;
    if(totalsuma<=13){EntradaIntegrador.setText(String.valueOf(contadorIntegrador));}
            
        
    }//GEN-LAST:event_AgregarIntegradorBTNActionPerformed

    private void EntradaNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaNivelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNivelesActionPerformed

    private void EntradaDLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDLCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDLCActionPerformed

    private void EntradaIntegradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaIntegradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaIntegradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarDLCBTN;
    private javax.swing.JButton AgregarIntegradorBTN;
    private javax.swing.JButton AgregarLogicaBTN;
    private javax.swing.JButton AgregarNivelesBTN;
    private javax.swing.JLabel DLCLabel;
    private javax.swing.JTextField EntradaDLC;
    private javax.swing.JTextField EntradaIntegrador;
    private javax.swing.JTextField EntradaLogica;
    private javax.swing.JTextField EntradaNarrativa;
    private javax.swing.JTextField EntradaNiveles;
    private javax.swing.JLabel IntegradorLabel;
    private javax.swing.JLabel LabelDevelop;
    private javax.swing.JLabel LogicaLabel;
    private javax.swing.JLabel NivelLabel;
    private javax.swing.JButton QuitarNarrativaBTN;
    private javax.swing.JButton RestarDLCBTN;
    private javax.swing.JButton RestarIntegradorBTN;
    private javax.swing.JButton RestarLogicaBTN;
    private javax.swing.JButton RestarNivelesBTN;
    private javax.swing.JButton agregarNarrativaBTN;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel narrativaLabel;
    // End of variables declaration//GEN-END:variables

    private int parseToString(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
